# Generated by Django 4.1.7 on 2023-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArHoldingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoarticulos',
            name='SKU',
            field=models.CharField(max_length=80),
        ),
    ]
