# Generated by Django 4.1.7 on 2023-03-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArHoldingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacioncliente',
            name='IdEncabezado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='ArHoldingsApp.facturacionencabezado'),
        ),
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='IdEncabezado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='ArHoldingsApp.facturacionencabezado'),
        ),
        migrations.AlterField(
            model_name='facturaciondetalle',
            name='SKU',
            field=models.CharField(max_length=20),
        ),
    ]
